package audit;

public enum AuditAction {
    AUTENTIFICARE_REUSITA, DELOGARE,
    PUBLICATIE_CREATA, PUBLICATIE_STEARSA,
    PUBLICATIE_IMPRUMUTATA, PUBLICATIE_RETURNATA,
    PUBLICATIE_REZERVATA, IMPRUMUT_REINNOIT,
    RECENZIE_ADAUGATA,
    CAUTARE_TITLU, CAUTARE_CATEGORIE, CAUTARE_INTERVAL_ANI,
    CAUTARE_DISPONIBILITATE, CAUTARE_COMPLEXA,
    SORTARE_AN, SORTARE_RATING, SORTARE_NR_IMPRUMUTURI, SORTARE_TITLU,
    UTILIZATOR_BLOCAT, UTILIZATOR_DEBLOCAT, BIBLIOTECAR_STAFF_CREAT,
    EVENIMENT_CREAT, EVENIMENT_STERS, INSCRIERE_EVENIMENT,
    LISTARE_EVENIMENTE,LISTARE_PUBLICATII,
    CITITOR_ADAUGAT,
    BIBLIOTECAR_ADAUGAT,
    REZERVARE_ADAUGATA
}
